### ISSUE TITLE
None of the 3D Touch items work with this tweak installed

### ISSUE THREAD

**Issue by JoeyEamigh** [alexPNG/CacheClearerX#4]
Developer AnthoPak of Appaze 2 thinks you may have inverted lines 271 and 272

[https://github.com/alexPNG/CacheClearerX/blob/master/Tweak.xm#L271](https://github.com/alexPNG/CacheClearerX/blob/master/Tweak.xm#L271)

**Comment by alexPNG** [comment]
I also forgot to turn the boolean values from the preferences to YES instead of NO. I’ll be fixing this later tonight and push v1.1. I’ll keep this issue open to check once I’ve issued the update to see if it’s fixed. I’ll let you know once I’ve updated it.

**Comment by alexPNG** [comment]
Pushed update for v1.1
Try the updated version and let me know if it's working now.

**Comment by JoeyEamigh** [comment]
Fixed!! Great job!
